title: Ilora Ishaque
logo: /images/avatar2.png
description: M.Eng. in Machine Learning from University of Cambridge. Looking for Data Science & Machine Learning Engineer roles
show_downloads: true
theme: jekyll-theme-minimal
